<script setup lang="ts">
import {onBeforeUnmount,onMounted,ref} from 'vue'
import ActivityLog from './components/ActivityLog.vue';import ConnectionBadge from './components/ConnectionBadge.vue';import CooktopPanel from './components/CooktopPanel.vue';import LevelSlider from './components/LevelSlider.vue';import LoginForm from './components/LoginForm.vue';import OnOffCard from './components/OnOffCard.vue';import WindowCoveringCard from './components/WindowCoveringCard.vue'
import {matterApi} from './services/apiClient';import {sseClient} from './services/sseClient';import {useActivityStore} from './stores/activity';import {useConnectionStore} from './stores/connection';import {useDeviceStore} from './stores/devices';import {useSessionStore} from './stores/session'
const nodeId='0x0000000000000001',session=useSessionStore(),connection=useConnectionStore(),devices=useDeviceStore(),activity=useActivityStore(),busy=ref(false);let rm1:(()=>void)|undefined,rm2:(()=>void)|undefined
function openEvents(){sseClient.connect()}async function login(username:string,password:string){busy.value=true;try{const s=await matterApi.login(username,password);session.set(s.username);openEvents()}catch(e){session.clear(e instanceof Error?e.message:'Login failed')}finally{busy.value=false}}async function logout(){await matterApi.logout();sseClient.disconnect();session.clear()}
onMounted(async()=>{rm1=sseClient.onMessage(m=>{devices.apply(m);activity.push(m)});rm2=sseClient.onConnection((ok,e)=>connection.update(ok,e));try{const s=await matterApi.session();session.set(s.username);openEvents()}catch{session.clear()}});onBeforeUnmount(()=>{rm1?.();rm2?.();sseClient.disconnect()})
</script>
<template><main class="mx-auto min-h-screen max-w-6xl px-5 py-10"><header class="mb-10 flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Matter over Thread</p><h1 class="mt-2 text-4xl font-bold tracking-tight text-white">Smart Home Gateway</h1><p class="mt-2 text-sm text-slate-400">Node {{nodeId}}</p></div><div v-if="session.authenticated" class="flex items-center gap-3"><ConnectionBadge/><button class="rounded-lg bg-white/10 px-3 py-2 text-sm" @click="logout">Logout</button></div></header><LoginForm v-if="!session.authenticated&&!session.loading" :busy="busy" :error="session.error" @login="login"/><template v-else-if="session.authenticated"><p v-if="connection.error" class="mb-5 rounded-xl bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{{connection.error}}</p><section class="grid gap-5 md:grid-cols-2"><OnOffCard :node-id="nodeId" :endpoint="1"/><LevelSlider :node-id="nodeId" :endpoint="1"/><WindowCoveringCard :node-id="nodeId" :endpoint="2"/><CooktopPanel :node-id="nodeId" :endpoint="3"/></section><div class="mt-5"><ActivityLog/></div></template><p v-else class="text-slate-400">Loading session…</p></main></template>
