<script setup lang="ts">
import {onBeforeUnmount,onMounted,ref} from 'vue'
import ActivityLog from './components/ActivityLog.vue';import ConnectionBadge from './components/ConnectionBadge.vue';import LoginForm from './components/LoginForm.vue';import OnOffCard from './components/OnOffCard.vue'
import {matterApi,type InventoryDevice} from './services/apiClient';import {sseClient} from './services/sseClient';import {useActivityStore} from './stores/activity';import {useConnectionStore} from './stores/connection';import {useDeviceStore} from './stores/devices';import {useSessionStore} from './stores/session'
const session=useSessionStore(),connection=useConnectionStore(),deviceState=useDeviceStore(),activity=useActivityStore(),busy=ref(false),inventory=ref<InventoryDevice[]>([]);let rm1:(()=>void)|undefined,rm2:(()=>void)|undefined
async function loadDevices(){inventory.value=(await matterApi.listDevices()).devices}
function openEvents(){sseClient.connect()}async function login(username:string,password:string){busy.value=true;try{const s=await matterApi.login(username,password);session.set(s.username);await loadDevices();openEvents()}catch(e){session.clear(e instanceof Error?e.message:'Login failed')}finally{busy.value=false}}async function logout(){await matterApi.logout();sseClient.disconnect();inventory.value=[];session.clear()}
async function removeDevice(nodeId:string){await matterApi.removeDevice(nodeId);await loadDevices()}
onMounted(async()=>{rm1=sseClient.onMessage(m=>{if('type' in m&&m.type==='provisioning'){if(m.state==='COMPLETE')void loadDevices();return}deviceState.apply(m);activity.push(m)});rm2=sseClient.onConnection((ok,e)=>connection.update(ok,e));try{const s=await matterApi.session();session.set(s.username);await loadDevices();openEvents()}catch{session.clear()}});onBeforeUnmount(()=>{rm1?.();rm2?.();sseClient.disconnect()})
</script>
<template><main class="mx-auto min-h-screen max-w-6xl px-5 py-10"><header class="mb-10 flex flex-wrap items-end justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.3em] text-cyan-300">Matter over Thread</p><h1 class="mt-2 text-4xl font-bold tracking-tight text-white">Smart Home Gateway</h1><p class="mt-2 text-sm text-slate-400">{{inventory.length}} commissioned device(s)</p></div><div v-if="session.authenticated" class="flex items-center gap-3"><ConnectionBadge/><button class="rounded-lg bg-white/10 px-3 py-2 text-sm" @click="logout">Logout</button></div></header><LoginForm v-if="!session.authenticated&&!session.loading" :busy="busy" :error="session.error" @login="login"/><template v-else-if="session.authenticated"><p v-if="connection.error" class="mb-5 rounded-xl bg-rose-400/10 px-4 py-3 text-sm text-rose-200">{{connection.error}}</p><p v-if="!inventory.length" class="rounded-xl bg-white/5 px-4 py-6 text-slate-400">No commissioned devices.</p><section v-for="device in inventory" :key="device.node_id" class="mb-5 rounded-xl bg-white/5 p-4"><div class="mb-4 flex items-center justify-between gap-3"><div><h2 class="font-semibold text-white">Rhophi device</h2><p class="text-xs text-slate-400">{{device.node_id}}</p></div><button class="rounded-lg bg-rose-400/10 px-3 py-2 text-sm text-rose-200" @click="removeDevice(device.node_id)">Remove</button></div><div class="grid gap-5 md:grid-cols-2"><OnOffCard v-for="endpoint in (device.descriptor.endpoints??[]).filter(item=>item.server_clusters?.includes(0x0006))" :key="endpoint.endpoint" :node-id="device.node_id" :endpoint="endpoint.endpoint"/></div></section><div class="mt-5"><ActivityLog/></div></template><p v-else class="text-slate-400">Loading session…</p></main></template>
